env: "local"

storage:
    host: "localhost"
    port: 5433
    database: "BlogApp"
    user: "postgres"
    password: "rootroot"
    migration: true
    logging: true
    max_idle_connection: 100

http_server:
  address: "localhost"
  port: "8888"
  timeout: 4s
  idle_timeout: 30s